### ISSUE TITLE
FATAL: password authentication failed for user "supabase_admin"

### ISSUE THREAD

**Issue by SteveChurch** [supabase-community/supabase-on-aws#12]
# Bug report

## Describe the bug
Fresh Cloud Formation deployment - ECS some tasks fail with `FATAL: password authentication failed for user "supabase_admin"`

## To Reproduce
Fresh deployment

Steps to reproduce the behaviour, please provide code snippets or a repository:

1. Fresh deploy to AWS - `eu-west-1`

## Expected behaviour

..

## Screenshots

<img width="1187" alt="image" src="https://user-images.githubusercontent.com/458008/215260192-3a6b96fa-12ac-405e-81fa-1b5ddb56bbae.png">
<img width="1409" alt="image" src="https://user-images.githubusercontent.com/458008/215260199-df5ad85d-41a9-4157-bd83-815e0f01302d.png">

## System information
....

**Comment by smcben** [comment]
spent a few hours figuring out why, that's either because the db password contains invalid characters such as `,` or because the password rotation code is rotating the password straight after generating one.

`const excludeCharacters = '%+~`#$&*()|[]{}:;<>?!\'/@\"\\=^,';` // added the comma there (supabase-db.ts)

also removed all the password rotation references, line 181 and in supabase-stack.ts:428

Then the whole thing should install.

But you'll find out that it runs 0.22.08 of supabase...

I tried upgrading to 0.22.11 and it's not happy, studio won't let you signup etc.

**Comment by klaus-metaz** [comment]
> spent a few hours figuring out why, that's either because the db password contains invalid characters such as `,` or because the password rotation code is rotating the password straight after generating one.
> 
> `const excludeCharacters = '%+~``#$&*()|[]{}:;<>?!'/@"\=^,';` // added the comma there (supabase-db.ts)
> 
> also removed all the password rotation references, line 181 and in supabase-stack.ts:428
> 
> Then the whole thing should install.
> 
> But you'll find out that it runs 0.22.08 of supabase...
> 
> I tried upgrading to 0.22.11 and it's not happy, studio won't let you signup etc.

@smcben Thank you so much! I manually changed the parameter values in the SSM and the Secrets Manager after seeing this and added the DB security group to the allowed inbound traffic sources to Auth and Rest Fargate services as well to make it work.

**Comment by bmeez** [comment]
@mats16 The solution @smcben provided works, but also required me to add a period to the string. I have a working string if you're interested in a PR.

**Comment by mats16** [comment]
@bmeez Thank you, I welcome you to create a PR!
Or if you send me the string I will correct it on my end. (There's another fix in the works.)
