### ISSUE TITLE
How to use RDS Postgres instead of RDS Aurora

### ISSUE THREAD

**Issue by adminaumo** [supabase-community/supabase-on-aws#57]
# Feature request

How to use RDS Postgres instead of RDS Aurora

## Is your feature request related to a problem? Please describe.

I need to use Supabase with the Postgres vector extension and apparently RDS Aurora v2 doesn't support this extension.

## Describe the solution you'd like

How do I generate or change the Cloudformation stack so that it creates the database on a traditional AWS RDS Postgres instance instead of using RDS Aurorar serverless?

**Comment by umuthopeyildirim** [comment]
I believe you can uncomment some code left to use RDS instance instead of cluster and try to synth your own template. I'm not sure if this will work you better try it out first. For example there are some code in `src/supabase-db/index.ts` like lines 23,38,76 to 93. Like I said I'm not 100% sure. @mats16 can confirm if it will work or not.

**Comment by mats16** [comment]
Thanks. @umuthopeyildirim is right.
And I can provide a CDK code for RDS with pgvector. But I have no idea to install [langchain-embedding_search](https://database.dev/langchain/embedding_search) without dbdev.

Do you know haw to install langchain-embedding_search without dbdev?

**Comment by mats16** [comment]
@adminaumo
I created a branch for RDS with pgvector.
https://github.com/supabase-community/supabase-on-aws/pull/59

Could you try it out? (CDK needed)

**Comment by mats16** [comment]
Today, Amazon Aurora supports pgvector!!
https://aws.amazon.com/about-aws/whats-new/2023/07/amazon-aurora-postgresql-pgvector-vector-storage-similarity-search/
